name: Deploy kbsb-demodash
run-name: Deploying kbsb-demodash (${{ github.actor }}).

on:
  push:
    branches:
    # - main
    - fs-117-ci-cd # test CI/CD config

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Build frontend
        run: make build
      - name: List dist folder
        run: ls dist
      - name: Create Rclone configuration file
        run: |
            echo "[scw]" > rclone.conf
            echo "type = s3" >> rclone.conf
            echo "provider = Scaleway" >> rclone.conf
            echo "env_auth = true" >> rclone.conf
            echo "region = nl-ams" >> rclone.conf
            echo "endpoint = s3.nl-ams.scw.cloud" >> rclone.conf
            echo "acl = private" >> rclone.conf
            echo "bucket_acl = private" >> rclone.conf
      - run: cat rclone.conf
      - run: echo "copy dist folder to Scaleway"
      - run: echo "purge Cloudflare cache"
      - env:
          TEST_VAR: ${{ secrets.TEST }}
        run: echo "$TEST_VAR"
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: python --version
      - run: make --version
