# production
# @URL = https://jchv4b5lpu5gea3lkowr5g2bei0tpnsl.lambda-url.eu-central-1.on.aws

# local dev server
@URL = http://100.111.214.8:8000

# https://github.com/Huachao/vscode-restclient/blob/master/README.md#variables

### endpoint: /

GET {{URL}}/ HTTP/1.1.
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT",
    "msg": "test",
    "httpMethod": "GET"
}

### endpoint: /new_todo

POST {{URL}}/new_todo HTTP/1.1.
content-type: application/json

{
    "body": {
        "description": "Desccc1",
        "label": "Normal",
        "done": true
    }
}
