# production
# @URL = https://XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.lambda-url.eu-central-1.on.aws

# local dev server
@URL = http://localhost:8000

# https://github.com/Huachao/vscode-restclient/blob/master/README.md#variables

### endpoint: /

GET {{URL}}/ HTTP/1.1.
content-type: application/json

{}

### endpoint: /new_todo

POST {{URL}}/new_todo HTTP/1.1.
content-type: application/json

{
  "description": "Lorem ipsum",
  "label": "normal",
  "done": true
}
